### PR TITLE
Volumes features

### PR DESCRIPTION
**Pull request by xilon-jul**
Proposal for milestone 0.2.5 
- volumes_from feature with ship checking
- container_volumes to handle defining volume with no host binding

### CODE REVIEW

**Comment by xilon-jul** [comment]
The build keeps failing but none of my commits define lambda function, it seems the flake8 does not like it. We should either allow the definition of lambda functions or change the code that uses lambdas. What do you think ?

**Comment by mpetazzoni** [comment]
Ah, it looks like a new version of flake8 is used and does this new check. I just committed and pushed the fix. You'll need to rebase and force push your branch for this PR to update itself with the fix.

Could you also remove the 3 "fix" commits and put their corresponding changes where appropriate in the original commits? I'd like to keep the history clean when merging. Thanks!

**Comment by xilon-jul** [comment]
Thanx for the fix. I made the history clean and pushed the modifications. We should be ready to merge soon !

**Comment by xilon-jul** [comment]
@mpetazzoni, the commit  53520cf is not working properly due to unserializable set into json format. Expected features volumes_from and container_volumes dont work.

**Comment by mpetazzoni** [comment]
Guess it's time to write unit tests and fix those :) I'll get on that today. Thanks

**Comment by mpetazzoni** [comment]
Alright, should be fixed now. Sorry about that!

**Pull request closed without merging**
