### PR TITLE
Add support for volume with no host bindind using schema version 3

### PR DESCRIPTION
**Pull request by xilon-jul**
Yaml 'volumes' key inverts logic with container/path: {'target': '/path/to/host', 'mode': <mode>}

### CODE REVIEW

**Comment by xilon-jul** [comment]
I would greatly appreciate if someone could help me so that the build can pass

**Comment by mpetazzoni** [comment]
Well, this is going to be a problem.

I just very recently inverted the volume mapping from `/in/container: /from/host` to `/from/host: /in/container` by request of many people that wanted Maestro's YAML to be declared in the same order Docker takes its volume mappings. Even thought I thought this was a bit restricting, since you could no longer have the same host directory mapped to multiple locations inside the container, the rationale that it behaved more like Docker made (some) sense.

I'm very reluctant to change it back again to support this. I'd rather we find another way of declaring volumes with no host bindings. I'm open to suggestions.

**Comment by xilon-jul** [comment]
Obviously, we are not going to change it back again, so we should propose a specific key under the instances YAML section that allows volume mapping only. I  will open another issue to start thinking about a new implementation to allow container volume only that best fits the way maestro has grown !

Thanx !

**Comment by xilon-jul** [comment]
We shoud also plan https://github.com/signalfuse/maestro-ng/issues/49 for milestone 0.2.5 as it also refers to volume

**Pull request closed without merging**
