### PR TITLE
Introduced logdriver (logconfig) support, including tests.

### PR DESCRIPTION
**Pull request by jverhoeven**
Added host_config to support log config. Added all start parameters to host_config as well, since they are deprecated on the container.start() and cause incorrect behavior. Removed the parameters from container start.

### CODE REVIEW

**Comment by mpetazzoni** [comment]
LGTM. Could you squash your commits together?

**Comment by mpetazzoni** [comment]
By the way make sure your `host_config` change is compatible with the version of `docker-py` that is listed in `requirements.txt` (otherwise it needs to be bumped up to match)

**Comment by jverhoeven** [comment]
Ok. Squashed it. Ran the tests with docker-py 1.3.0 which the current minimum and checked the release notes. Seems all ok.

**Comment by mpetazzoni** [comment]
Thanks!

**Pull request merged**
